/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Convolution2D */

#ifndef _Included_Convolution2D
#define _Included_Convolution2D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Convolution2D
 * Method:    nativeConvolution
 * Signature: ([[F[[F)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_Convolution2D_nativeConvolution
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
